name: onusworks_albums_app
description: Onusworks Albums viewer application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_styled_toast: ^2.2.1
  hive: ^2.2.3
  intl: ^0.18.1
  path_provider: ^2.1.2
  sqflite: ^2.3.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.6
  build_runner: 2.4.8
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  generate: true
